### ISSUE TITLE
Informal accessibility testing

### ISSUE THREAD

**Issue by NiallBoyd** [NiallBoyd/ecommerce-pattern-library#2]
- [x] Text size up (2 sizes)
- [x] Text size down (2 sizes)
- [x] Alt attribute tests (this needs to be restructured a bit better)
- [x] Heading structure & outline
- [x] ARIA implementation (tested but needs to be added into the patterns)
- [x] Focus styles
- [x] Skip links
- [x] Colour contrast
- [x] Link obviousness

I used my web developer toolbar and everything worked perfectly!

Need to add aria labels and alt description on images and buttons.

@thomasjbradley

**Comment by thomasjbradley** [comment]
👍
