### ISSUE TITLE
Informal browser testing

### ISSUE THREAD

**Issue by NiallBoyd** [NiallBoyd/ecommerce-pattern-library#3]
**Screen sizes**

- [x] Tested on all screen widths in all browsers
- [x] Tested on all screen heights in all browsers
- [x] Portrait orientation tested
- [x] Landscape orientation tested
- [x] Full screen browsers tested

**Functionality**

- [x] All user interactions have been user tested
- [x] All different page layouts have been tested
- [x] Tested with a range of default font sizes: 2 bigger, 2 smaller
- [x] Tested with images disabled
- [x] Tested with CSS disabled
- [x] Standard resolution monitors tested
- [x] Retina resolution monitors tested
- [x] Tested in low-bandwidth situations
- [x] Tested with common ad blockers

**Operating systems**

- [x] MacOS
- [x] Android OS
- [ ] iOS

- Mobile navigation needs to be fixed 
- Chrome images do not appear 

@thomasjbradley

**Comment by thomasjbradley** [comment]
👍
